[package]
name = "rhyterm"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = "0.18"
crossterm = "0.24"
rodio = "0.17"
hound = "3.4.0"
rustfft = "5.1.0"
num-complex = "0.4"
plotters = "0.3"
id3 = "0.4"
flac = "0.4"